config/routes.rb
Rails.application.routes.draw do

  namespace :public do
   
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  root 'public/homes#top'
  get '/about' => 'public/homes#about'


  scope module: :public do
    # 商品
    resources :items, only: [:index,:show]
    # 配送先
    resources :addresses, only: [:index,:create,:edit,:update,:destroy]
    # カート
    resources :cart_items, only: [:index,:create,:update,:destroy]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }

  namespace :admin do
    root "homes#home"
    resources :customers, only: [:index,:show,:edit,:update]
    resources :genres
    resources :items, only: [:new,:create,:index,:show,:edit,:update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
      # blank?メソッドは、オブジェクトが空白の場合はtrueを返し,
      # オブジェクトが空白ではない場合はfalseを返すメソッド
    # else @genre.name.blank?
    else
      @genres = Genre.all
      render 'index'
    end
  end

  def show
    @genre = Genre.find(params[:id])
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private

    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <h5 class="col-md-7 mb-5 mt-5">
    <span class="py-2 px-4 bg-ligh alert-secondary">ジャンル編集</span>
  </h5>
  <div class="row mt-5">
    <%= form_with model: @genre,url:admin_genre_path,local:true do |f| %>
      <div>
        <span class="mr-5">ジャンル名</span>
        <%= f.text_field :name %>
        <%= f.submit "変更を保存", class: "ml-5 btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h5 class="col-md-7 mb-5 mt-5">
      <span class="px-3 ml-5 bg-ligh alert-secondary">ジャンル一覧・追加</span>
    </h5>

    <div class="row">
      <div class="col-10">
      <%= form_with url: admin_genres_path, model: @genre, local: true do |f| %>

        <table class="tab">
          <td><strong><%= f.label :name, 'ジャンル名', class: "mr-5" %></strong></td>
          <td><%= f.text_field :name, class: 'form-control' %></td>
          <td><%= f.submit '新規登録', class: 'btn btn-success ml-5' %></td>
        </table>
       <% end %>
    </div>
    </div>
    <div class="row">
      <div  class="col-5">
        <table class="table table-hover table-inverse  mt-5" >
        <thead class="thead-light">
            <th>
              ジャンル
            </th>
            <th></th>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
            <tr>
              <td>
                <%= genre.name %>
              </td>
              <td align="center">
                <%= link_to "編集する",edit_admin_genre_path(genre), class: "btn btn-success" %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>

    </div>
  </div>
</div>